a = int(input("Nhập số a: "))
b = int(input("Nhập số b: "))
tich = abs(a * b)
temp_a, temp_b = abs(a), abs(b)
while temp_b != 0:
    temp_a, temp_b = temp_b, temp_a % temp_b
ucln = temp_a
bcnn = tich // ucln
print(f"UCLN({a}, {b}) = {ucln}")
print(f"BCNN({a}, {b}) = {bcnn}")